/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as identityCom from "./@identity.com";
export type { identityCom };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Gated } from "./@identity.com/gateway-protocol-eth/contracts/Gated";
export { Gated__factory } from "./factories/@identity.com/gateway-protocol-eth/contracts/Gated__factory";
export type { IGatewayTokenVerifier } from "./@identity.com/gateway-protocol-eth/contracts/interfaces/IGatewayTokenVerifier";
export { IGatewayTokenVerifier__factory } from "./factories/@identity.com/gateway-protocol-eth/contracts/interfaces/IGatewayTokenVerifier__factory";
export type { Airdrop } from "./contracts/Airdrop";
export { Airdrop__factory } from "./factories/contracts/Airdrop__factory";
export type { IERC20 } from "./contracts/IERC20";
export { IERC20__factory } from "./factories/contracts/IERC20__factory";
